# Generated by Django 5.1.7 on 2025-03-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slig',
            new_name='slug',
        ),
    ]
